#!/bin/bash
set -e

# Symlink the 12factor directory for convenience
ln -nfs "/var/run/12factor" "/12factor"

# Execute each initialization cloud-config in alphabetical order
find "/12factor/init.d" -type f -name '*.yml' | sort | while read f; do coreos-cloudinit --from-file="$f"; done

# Execute each initialization script in alphabetical order
find "/12factor/init.d" -type f -name '*.sh' | sort | while read f; do "$f"; done
