#!/bin/bash
set -e

# Symlink the 12factor directory for convenience
ln -nfs "/var/run/12factor" "/12factor"

# Execute each initialization script in alphabetical order
find "/12factor/init.d" -mindepth 1 -maxdepth 1 | sort | \
  while read init_script; do
    "$init_script"
  done
