#!/bin/bash
set -e

# Set environment
COMMAND="$1"

# Look for known command aliases
case "${COMMAND}" in
  "init" | "conf" )
    shift
    # Execute each deploy script in order
    find "./deploy.d" -type f | sort | while read f; do MODE=${COMMAND} "$f"; done
    exec "$@"
    ;;
  * )
    exec "$@"
    ;;
esac
