#!/bin/bash
set -e

# Set environment variables
ETCD_ENVIRONMENT_VARIABLE_REGEX="^\s*ETCD2ENV_([_A-Z0-9]+)=(.+)\s*$"
ENV_FILE="/12factor/env/etcd2env.env"

# Build a combined environment file for use in systemd services
cat << EOF > "${ENV_FILE}"
# Do not edit this file.  It is automatically generated by the etcd environment
# configuration service
EOF
while read -r env_name etcd_variable ; do
  env_value=$(/usr/bin/etcdctl get "${etcd_variable}")
  if [ -z "${env_value}" ]; then
    echo >&2 "Unable to load ${etcd_variable} variable from etcd."
    exit 1
  fi
  echo "${env_name}=${env_value}" >> "${ENV_FILE}"
done < <(env | grep -E "${ETCD_ENVIRONMENT_VARIABLE_REGEX}" | sed -E "s/${ETCD_ENVIRONMENT_VARIABLE_REGEX}/\1 \2/" | sort | uniq)
