#!/bin/bash
set -e

# This is the first stage initialization and is reponsible for creating directories,
# files, links and setting up any required environment first in preparation for
# second stage initialization.  This stage should NOT perform anything complicated
# such as docker operations.

# Symlink the 12factor directory for convenience
ln -nfs "/var/run<%= get(:config_directory) %>" "<%= get(:config_directory) %>"

# Move the stage 2 init service directly to the systemd run directory
if [ -f "<%= get(:config_directory) %>/systemd/12factor-init-stage-two.service" ]; then
  mv -fv "<%= get(:config_directory) %>/systemd/12factor-init-stage-two.service" "/var/run/systemd/system"
fi

# Create symlinks for all systemd units in the systemd directory
find "<%= get(:config_directory) %>/systemd" -type f | while read f; do
  ln -fsv "$f" "/var/run/systemd/system/`basename $f`"
done

# Create symlinks for all scipts to the /opt/bin directory without the .sh extension
# for convenience
mkdir -p "/opt/bin"
find "<%= get(:config_directory) %>/script" -type f -iname "*.sh" | while read f; do
  ln -fsv "$f" "/opt/bin/`basename ${f%.sh}`"
done

# Create a symlink for the environment profile
mkdir -p "/etc/profile.d"
ln -fsv "<%= get(:config_directory) %>/env/profile.sh" "/etc/profile.d/12factor-env.sh"

# Reload the systemctl daemon to load any new systemd units
systemctl daemon-reload

# Start the stage two initialization and exit
systemctl start 12factor-init-stage-two &

exit 0
