#!/bin/bash
set -e

# This is the second stage initialization and is responsible for bringing up the
# application from scrach, which includes downloading required docker images and
# running services.  The second stage is divided into separate configs and/or
# scripts located in the init.d directory, which are executed in alphabetical
# order serially.  Note however that cloud-config yml initializers are spawned
# in parallel and cannot be guaranteed to run in order.

# Pre-pull all docker images at the start to ensure a smoother initialization
echo "Pre-pulling all required docker images"
systemctl start docker-check-image-update.service
echo "Finished pre-pulling all required docker images"

# Notify that we started
/opt/bin/send-notification warn "Starting \`twelve-factor\` initialization"

# (Re-)create the twelve-factor configuration volume container
if ! [ -z "${DOCKER_IMAGE_12FACTOR_CONFIG}" ] && ! [ -z "${DOCKER_CONTAINER_12FACTOR_CONFIG}" ]; then
  /opt/bin/docker-check-pull ${DOCKER_IMAGE_12FACTOR_CONFIG}
  /opt/bin/docker-check-remove ${DOCKER_CONTAINER_12FACTOR_CONFIG}
  /usr/bin/docker run \
    --label ${DOCKER_VOLUME_CONTAINER_LABEL} \
    --label ${DOCKER_CONTAINER_12FACTOR_CONFIG} \
    --hostname ${DOCKER_HOSTNAME} \
    -e STAGE=<%= get(:stage) %> \
    -e ROLE=<%= get(:role) %> \
    --name ${DOCKER_CONTAINER_12FACTOR_CONFIG} \
    ${DOCKER_IMAGE_12FACTOR_CONFIG} \
    container
fi

# Create the twelve-factor data volume container if not already created
if ! [ -z "${DOCKER_IMAGE_12FACTOR_DATA}" ] && ! [ -z "${DOCKER_CONTAINER_12FACTOR_DATA}" ]; then
  /opt/bin/docker-check-pull ${DOCKER_CONTAINER_12FACTOR_DATA}
  if [ -z "$(docker ps --no-trunc -a -q -f label=${DOCKER_CONTAINER_12FACTOR_DATA})" ]; then
    /usr/bin/docker run \
      --label ${DOCKER_VOLUME_CONTAINER_LABEL} \
      --label ${DOCKER_CONTAINER_12FACTOR_DATA} \
      --volume <%= get(:data_directory) %> \
      --name ${DOCKER_CONTAINER_12FACTOR_DATA} \
      ${DOCKER_IMAGE_12FACTOR_DATA}
  fi
fi

# Start base systemd services and wait
systemctl start install-tools.service &
if ! [ -z "${SWAP_FILE_SIZE}" ]; then
  systemctl start swapfile.service &
fi
if ! [ -z "${NEWRELIC_LICENSE_KEY}" ]; then
  systemctl start newrelic-agent.service &
fi
if ! [ -z "${ETCD_DISCOVERY_URL}" ]; then
  systemctl start etcdd.service &
  systemctl start etcd2env.service &
fi
wait

# Execute each initialization cloud-config or script in alphabetical order
find "<%= get(:config_directory) %>/init.d" -type f | sort | uniq | while read file; do
  if [[ "$file" == *.yml ]]; then
    echo "Executing twelve-factor initialization cloud-config $file..."
    coreos-cloudinit --from-file="$file"
  fi
  if [[ "$file" == *.sh ]]; then
    echo "Executing twelve-factor initialization script $file..."
    "$file"
  fi
done

# Start services listed in the systemd start file
if [ -f "<%= get(:config_directory) %>/systemd/start" ]; then
  cat "<%= get(:config_directory) %>/systemd/start" | sort | while read unit; do
    systemctl start $unit &
  done
  wait
fi

# Notify that we finished
/opt/bin/send-notification success "Finished \`twelve-factor\` initialization"

exit 0
