#!/bin/bash
set -e

# This is the first stage initialization and is reponsible for creating directories,
# files, links and setting up any required environment first in preparation for
# second stage initialization.  This stage should NOT perform anything complicated
# such as docker operations.

# Abort stage one if environment is set
if [ "${ABORT_PARASITE_INIT_STAGE_ONE}" = "true" ]; then
  echo >&2 "Aborting parasite stage one initialization per ABORT_PARASITE_INIT_STAGE_ONE environment variable"
  exit 1
fi

# Make sure we are running at root
if ! [ "$(whoami)" = "root" ]; then
  echo >&2 "Parasite stage one initialization must be run as root!"
  exit 1
fi

# Make sure the parasite environment file is in place
if ! [ -f "/parasite-config.env" ]; then
  echo >&2 "Missing parasite initialization environment file /parasite-config.env!"
  exit 1
fi

# Copy the docker configuration file from root to the parasite user home to ensure we
# don't get authentication problems with docker regardless of user
mkdir -p "/home/<%= getenv!(:parasite_user) %>/.docker"
cp -fv "/root/.docker/config.json" "/home/<%= getenv!(:parasite_user) %>/.docker/config.json"
chown -R <%= getenv!(:parasite_user) %>:<%= getenv!(:parasite_user) %> "/home/<%= getenv!(:parasite_user) %>/.docker"

# Symlink the parasite directory to the root
ln -nfs "/var/run<%= getenv!(:config_directory) %>" "<%= getenv!(:config_directory) %>"

# Move the stage 2 init service directly to the systemd run directory
if [ -f "<%= getenv!(:config_directory) %>/systemd/parasite-init-stage-two.service" ]; then
  mv -fv "<%= getenv!(:config_directory) %>/systemd/parasite-init-stage-two.service" "/var/run/systemd/system"
fi

# Create symlinks for all systemd units in the systemd directory
find "<%= getenv!(:config_directory) %>/systemd" -type f \( -name "*.path" -or -name "*.service" -or -name "*.timer" \) | while read f; do
  ln -fsv "$f" "/var/run/systemd/system/`basename $f`"
done

# Create symlinks for all scipts to the /opt/bin directory without the .sh extension
# for convenience
mkdir -p "/opt/bin"
find "<%= getenv!(:config_directory) %>/script" -type f -iname "*.sh" | while read f; do
  ln -fsv "$f" "/opt/bin/`basename ${f%.sh}`"
done

# Create a symlink for the environment profile
mkdir -p "/etc/profile.d"
ln -fsv "<%= getenv!(:config_directory) %>/env/profile.sh" "/etc/profile.d/parasite-env.sh"

# Reload the systemctl daemon to load any new systemd units
systemctl daemon-reload

# Start the stage two initialization and exit
systemctl start parasite-init-stage-two &

exit 0
