#!/bin/bash
set -e

# This is the first stage initialization and is reponsible for creating directories,
# files, links and setting up any required environment first in preparation for
# second stage initialization.  This stage should NOT perform anything complicated
# such as docker operations.

# Create a host data directory
mkdir -p "<%= getenv!(:parasite_data_directory) %>"

# Make sure we are running at root
if ! [ "$(whoami)" = "root" ]; then
  echo >&2 "Parasite stage one initialization must be run as root!"
  exit 1
fi

# Copy the docker configuration file from root to the parasite user home to ensure we
# don't get authentication problems with docker regardless of user
mkdir -p "/home/<%= getenv!(:parasite_user) %>/.docker"
cp -fv "/root/.docker/config.json" "/home/<%= getenv!(:parasite_user) %>/.docker/config.json"
chown -R <%= getenv!(:parasite_user) %>:<%= getenv!(:parasite_user) %> "/home/<%= getenv!(:parasite_user) %>/.docker"

# Create symlinks for all systemd units in the systemd directory
find "<%= getenv!(:parasite_config_directory) %>/systemd" -type f \( -name "*.mount" -or -name "*.path" -or -name "*.service" -or -name "*.timer" \) | while read f; do
  ln -fsv "$f" "/var/run/systemd/system/`basename $f`"
done

# Create symlinks for all scipts to the /opt/bin directory without the .sh extension
mkdir -p "/opt/bin"
find "<%= getenv!(:parasite_config_directory) %>/script" -type f -iname "*.sh" | while read f; do
  ln -fsv "$f" "/opt/bin/`basename ${f%.sh}`"
done

# Create symlinks for logrotate configurations
rm -f /etc/logrotate.d/*.conf
find "<%= getenv!(:parasite_config_directory) %>/logrotate.d" -type f \( -name "*.conf" \) | while read f; do
  ln -fsv "$f" "/etc/logrotate.d/`basename $f`"
done

# Create a symlink for the environment profile
mkdir -p "/etc/profile.d"
ln -fsv "<%= getenv!(:parasite_config_directory) %>/env/parasite-profile.env" "/etc/profile.d/parasite-profile.sh"

# Reload the systemctl daemon to load any new systemd units
systemctl daemon-reload

# Start the stage two initialization and exit
systemctl start parasite-init-stage-two &

exit 0
