#!/bin/sh
set -e

# This is the second stage initialization and is responsible for bringing up the
# application from scrach, which includes downloading required docker images and
# running services.

# Check for unsupported Docker version
# ! [[ $(docker version --format '{{.Server.Version}}') =~ ^1\s*\.1[0-2]\.[0-9]+\s*$ ]] && \
#   echo >&2 "Docker version must be at least 1.10.x" && \
#   exit 1

# Create the default bridge network and extract the bridge network address
/usr/bin/docker network rm <%= getenv!(:parasite_docker_bridge_network) %> || true
/usr/bin/docker network create --driver=bridge <%= getenv!(:parasite_docker_bridge_network) %>

# Attempts to start a systemd unit if it exists
start_unit() {
  systemd_unit=$1
  # Return silently if the unit doesn't exist
  systemctl status ${systemd_unit} | grep "Loaded: not-found" >/dev/null 2>&1 && return
  systemctl start ${systemd_unit}
}

# Notify that we started
/opt/bin/send-notification warn "Starting \`docker-parasite\` initialization"

# Pre-pull all docker images at the start to ensure a smoother initialization
/opt/bin/send-notification warn "Checking for newer docker images"
start_unit docker-check-image-update.service
/opt/bin/send-notification success "Finished checking for newer docker images"

# Restore existing parasite data from backup archive if present
[ -f "/<%= getenv!(:parasite_data_backup_archive) %>" ] && \
  /opt/bin/parasite-data-restore && \
  mv "/<%= getenv!(:parasite_data_backup_archive) %>" "/<%= getenv!(:parasite_data_backup_archive) %>.restored"

# Execute each system startup script in alphabetical order
find "<%= getenv!(:parasite_config_directory) %>/startup" -type f | sort | uniq | while read file; do
  /opt/bin/send-notification warn "Executing \`$(basename ${file})\` parasite startup script..."
  su -c "${file}"
  /opt/bin/send-notification success "Finished executing \`$(basename ${file})\` parasite startup script."
done

# Start services listed in the systemd start file
if [ -f "<%= getenv!(:parasite_config_directory) %>/systemd/start" ]; then
  cat "<%= getenv!(:parasite_config_directory) %>/systemd/start" | sort | while read unit; do
    start_unit ${unit} &
  done
  wait
fi

# Notify that we finished
/opt/bin/send-notification success "Finished \`docker-parasite\` initialization"

exit 0
