#!/bin/bash
set -e

# This is the second stage initialization and is responsible for bringing up the
# application from scrach, which includes downloading required docker images and
# running services.  The second stage is divided into separate configs and/or
# scripts located in the init.d directory, which are executed in alphabetical
# order serially.  Note however that cloud-config yml initializers are spawned
# in parallel and cannot be guaranteed to run in order.

# Pre-pull all docker images at the start to ensure a smoother initialization
echo "Pre-pulling all required docker images"
systemctl start docker-check-image-update.service
echo "Finished pre-pulling all required docker images"

# Notify that we started
/12factor/bin/send-notification warn "Starting \`twelve-factor\` initialization"

# Create the twelve-factor configuration data volume container
if ! [ -z "${DOCKER_CONTAINER_12FACTOR_CONFIG}" ] && ! [ -z "${DOCKER_IMAGE_COREOS_12FACTOR}" ]; then
  /12factor/bin/docker-check-remove ${DOCKER_CONTAINER_12FACTOR_CONFIG}
  /usr/bin/docker run \
    -e VM_HOSTNAME=$(hostname) \
    --label data \
    --name ${DOCKER_CONTAINER_12FACTOR_CONFIG} \
    ${DOCKER_IMAGE_COREOS_12FACTOR} \
    conf
fi

# Start base systemd services and wait
systemctl start install-tools.service &
if ! [ -z "${SWAP_FILE_SIZE}" ]; then
  systemctl start swapfile.service &
fi
if ! [ -z "${NEWRELIC_LICENSE_KEY}" ]; then
  systemctl start newrelic-sysmond.service &
fi
if ! [ -z "${ETCD_DISCOVERY_URL}" ]; then
  systemctl start etcdd.service &
fi
wait

# Execute each initialization cloud-config or script in alphabetical order
find "/12factor/init.d" -type f | sort | uniq | while read file; do
  if [[ "$file" == *.yml ]]; then
    echo "Executing twelve-factor initialization cloud-config $file..."
    coreos-cloudinit --from-file="$file"
  fi
  if [[ "$file" == *.sh ]]; then
    echo "Executing twelve-factor initialization script $file..."
    "$file"
  fi
done

# Start services listed in the systemd start file
if [ -f "/12factor/systemd/start" ]; then
  cat "/12factor/systemd/start" | sort | while read unit; do
    systemctl start $unit &
  done
  wait
fi

# Notify that we finished
/12factor/bin/send-notification success "Finished \`twelve-factor\` initialization"

exit 0
