#!/bin/bash
set -e

# This is the second stage initialization and is responsible for bringing up the
# application from scrach, which includes downloading required docker images and
# running services.  The second stage is divided into separate configs and/or
# scripts located in the init.d directory, which are executed in alphabetical
# order serially.  Note however that cloud-config yml initializers are spawned
# in parallel and cannot be guaranteed to run in order.

# Pre-pull all docker images at the start to ensure a smoother initialization
echo "Pre-pulling all required docker images"
systemctl start docker-check-image-update.service
echo "Finished pre-pulling all required docker images"

# Notify that we started
/12factor/bin/send-notification warn "Starting \`twelve-factor\` initialization"

# Start base systemd services and wait
if ! [ -z "${SWAP_FILE_SIZE}" ]; then
  systemctl start swapfile.service &
fi
if ! [ -z "${NEWRELIC_LICENSE_KEY}" ]; then
  systemctl start newrelic-sysmond.service &
fi
systemctl start tools-install.service &
systemctl start docker-check-image-update.timer &
systemctl start docker-cleanup.timer &
wait

# Execute each initialization cloud-config or script in alphabetical order
find "/12factor/init.d" -type f | sort | uniq | while read file; do
  if [[ "$file" == *.yml ]]; then
    echo "Executing twelve-factor initialization cloud-config $file..."
    coreos-cloudinit --from-file="$file"
  fi
  if [[ "$file" == *.sh ]]; then
    echo "Executing twelve-factor initialization script $file..."
    "$file"
  fi
done

# Start services listed in the systemd start file
if [ -f "/12factor/systemd/start" ]; then
  cat "/12factor/systemd/start" | sort | while read unit; do
    systemctl start $unit &
  done
  wait
fi

# Notify that we finished
/12factor/bin/send-notification success "Finished \`twelve-factor\` initialization"

exit 0
