#!/bin/bash
set -e

# Symlink the 12factor directory for convenience
ln -nfs "/var/run/12factor" "/12factor"

# Create a data directory and link it into the 12factor directory
mkdir -p "/data"
mkdir -p "/data/docker/ids" && chmod 777 "/data/docker/ids"
mkdir -p "/data/docker/logs" && chmod 777 "/data/docker/logs"
ln -nfs "/data" "/12factor/data"

# Create required subdirectories
mkdir -p "/12factor/auth"
mkdir -p "/12factor/bin"
mkdir -p "/12factor/conf"
mkdir -p "/12factor/env"
mkdir -p "/12factor/env.d"
mkdir -p "/12factor/script"
mkdir -p "/12factor/unit"

# Create symlinks for all scipts in the bin directory without the .sh extension
# for convenience
find "/12factor/script" -type f -iname "*.sh" | while read f; do
  ln -fsv "$f" "/12factor/bin/`basename ${f%.sh}`"
done

# Create symlinks for all systemd units in the systemd directory
find "/12factor/unit" -type f | while read f; do
  ln -fsv "$f" "/var/run/systemd/system/`basename $f`"
done

# Run the environment configuration script to generate consolidated environment
# files for use in systemd services and docker containers
/12factor/bin/environment-config

# Start the stage two initialization
systemctl start 12factor-init-stage-two
